Add finetuning to nats client settings. Make running bosh actions after a director recreate more reliable.
cloudfoundry/bosh-agent pull request #284
Opened 2022-05-23 09:42 UTC by nouseforaname

The additional logging that was added has shown that the agent eventually exits with the following error:
`ErrNoServers = errors.New("nats: no servers available for connection")` from the nats library.  

Additionally, the `c.Reconnects` counter didn't increment. It turns out setting `nats.RetryOnFailedConnect(true)`
option is also required to actually do reconnects not just retries.

Remove nats maxConnectionRetries and replace with indefinite retries. We don't actually want the agent to give up reconnecting. So it shouldn't ever run out of attempts on a longer than usual bosh recreate.

Add Arping to bosh address to make sure cache is not only flushed but also filled with right value on reconnect.
Currently the Arp resolution is probably done via the OS at some point and making it explicit should make it happen exactly
when we run the reconnect attempt.

Remove fmt.sprintfs in logging calls, they're unnecessary

Lower `reconnectWait` to 10 seconds. in testing it was found that `agent timed out just after a director recreate`
still happens even though the agents are not crashing anymore.

Increase sleep between arpClean calls, no need in running it every second. It should lower the load on the director even
though we set the maxReconnectWait to 10 seconds.

2022-06-07 12:06 UTC, beyhan requested changes

2022-06-07 13:13 UTC, nouseforaname commented on mbus/nats_handler.go
> +		nats.MaxReconnects(-1),
yes

2022-06-09 14:44 UTC, beyhan approved these changes

2022-06-09 14:49 UTC, lnguyen approved these changes

2022-06-09 14:51 UTC, merged