Add StripVolumeRegex configuration property
cloudfoundry/bosh-agent pull request #311
Opened 2023-06-15 07:11 UTC by ten4o

Add a `StripVolumeRegex` configuration property that will be used to strip some part of `disk-id` (aka volume ID) before device path resolve step, as proposed by the Working Group:

_Create a configuration property for the bosh agent to configure a strip-volume-regex,
which would allow specifying a regex prefix per IaaS in the bosh stemcell builder [here](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ubuntu-jammy/master/stemcell_builder/stages/bosh_alicloud_agent_settings/apply.sh#L11-L1) (in the case of Ali Cloud)._

The potential benefit is that this could solve issue #310.

2023-06-20 14:28 UTC, beyhan requested changes

2023-06-27 11:58 UTC, beyhan approved these changes

2023-06-27 12:18 UTC, beyhan commented
The change looks good. One open question is whether we need integration tests for it. I couldn't find any ITs for this kind of functionality.

2023-06-27 15:57 UTC, ramonskie commented
as we currently only do bats testing on gcp. i don't know if this pr actually solves it for this.
but if so we can maby fit is somewhere here https://github.com/cloudfoundry/bosh-acceptance-tests/blob/master/spec/bat/bosh_helper_spec.rb#L29

2023-06-28 09:05 UTC, beyhan commented
We want to make use of this only on AWS and Ali for now. On GCP stripping disk IDs isn't required. I was thinking for agent integration tests and not bosh.

2023-06-29 14:50 UTC, rkoster commented
There are some integration test helpers like [AttachDevice](https://github.com/cloudfoundry/bosh-agent/blob/main/integration/test_environment.go#L321) which could be helpful when adding an integration test.

2023-07-03 05:43 UTC, andinod commented
Hi, 

one question, is this change considering the Openstack Env?, because I have a similar issue described here [https://github.com/cloudfoundry/bosh-agent/issues/310#issuecomment-1611380262](https://github.com/cloudfoundry/bosh-agent/issues/310#issuecomment-1611380262) and I would like to know if I need to wait or there is a workaround that I have to look for.

Thanks in advance,

David

2023-07-03 07:11 UTC, beyhan commented
Hi @andinod,
this change will enable us to configure a prefix which could be removed from the disk ID on the different IaaS providers. That means configuration like [this](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ubuntu-jammy/master/stemcell_builder/stages/bosh_alicloud_agent_settings/apply.sh#L11-L13) will be required for an IaaS provider so that this can have an affect as discussed [here](https://github.com/cloudfoundry/bosh-agent/pull/309#issuecomment-1572247146).

2023-07-03 07:45 UTC, beyhan commented
Regarding the IT discussion:
I think that it make sense to add a test case to the [AssociateDisk](https://github.com/cloudfoundry/bosh-agent/blob/main/platform/linux_platform_test.go#L3575-L3605) tests in the [linux_platform_test.go](https://github.com/cloudfoundry/bosh-agent/blob/main/platform/linux_platform_test.go). The settings should look like [this](https://github.com/cloudfoundry/bosh-agent/blob/main/integration/assets/file-settings-agent.json) so that the right provider is selected [here](https://github.com/cloudfoundry/bosh-agent/blob/main/platform/provider.go#L116-L121). Additionally, we should configure a strip value and verify that the ID resolution worked. @jpalermo, @rkoster  what opinion on this? Are the agent integration tests executable locally because our [agent dev setup](https://github.com/cloudfoundry/bosh-agent/blob/main/docs/dev_setup.md) is not clear about this and I didn't have time to try it?

2023-07-06 14:04 UTC, rkoster approved these changes

2023-07-06 14:41 UTC, beyhan requested changes
Please try to add the integration test as I described it in my previous comment.

2023-07-10 14:29 UTC, ten4o commented
@beyhan After examining `AssociateDisk` tests, it seems that those are the unit tests of `linux_platform.go` - all test cases in that file are using `FakeDevicePathResolver` which will not call our code in `GetRealDevicePath`. It seems that there is not much value in hacking together additional test cases in `AssociateDisk` when we can already add similar test cases in `identity_device_path_resolver_test.go`.

2023-07-12 14:27 UTC, beyhan commented
Ok, I looked into the wrong tests. Looking into the right tests I think an integration test will be challenging to implement here because the agent handles the resolution internally during the [update_setttings](https://github.com/cloudfoundry/bosh-agent/blob/main/agent/action/update_settings.go#L44-L81) action. The only way to validate from outside that the [id_device_path_resolver.go](https://github.com/cloudfoundry/bosh-agent/blob/main/infrastructure/devicepathresolver/id_device_path_resolver.go) provider was used, is via logs which is error prone.

2023-07-13 14:45 UTC, beyhan approved these changes
We agreed to go without integration tests.

2023-07-13 14:45 UTC, merged